---
all:
  [apache]
  hosts:
    server1:
    server2:
  children:
    dns:
      hosts:
        server0:
    haproxy:
      hosts:
        server0:
    wordpress:
      hosts:
        server1:
        server2:
    mariadb:
      hosts:
        server3:
    nfsserver:
      hosts:
        server4:
